name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files src/*.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make

      - name: Test
        run: make test

      - name: Clean up
        run: make clean
